name: CleanUpMonoRepo
repository: https://github.com/aafiqah/clean_up_community_app
packages:
  - packages/**

scripts:
  bs: |
    melos bootstrap
  analyze: |
    melos run analyze
  test: |
    melos run test
  get:
    run: melos exec -- flutter pub get
  gen-assets:
    run: melos exec -- dart run build_runner build
    description: Generate models

flutter:
  sdkPath: /path/to/flutter/sdk
