name: clean_up_community_melos

packages:
  - apps/clean_up
  - packages/**

flutter:
  assets:
    - apps/clean_up/assets/icons/
    - apps/clean_up/assets/images/

command:
  bootstrap:
    usePubspecOverrides: true
    runPubGetInParallel: true
