name: clean_up_community_app
description: "Clean Up Community Mobile Root"
publish_to: 'none'
version: 1.1.0+6

environment:
  sdk: ^3.9.2

workspace:
  - apps/clean_up

dev_dependencies:
  melos: ^6.3.2