import '../../domain/index.dart';

class UpcomingEventDataSource {
  static List<UpcomingEvent> getEvents() {
    return [
      UpcomingEvent(
        eventName: 'Kempen Membersihkan Pantai',
        eventDate: '10 April 2025',
        eventTime: '08:00 AM - 10:30 AM',
        eventLocation: UpcomingEventLocation(
          eventAddressOne: 'Jalan Pantai Desaru',
          eventAddressTwo: 'Sebelah Resort Desaru',
          eventState: 'Johor',
          eventPasscode: '81930',
          eventCity: 'Desaru',
          eventLatitude: '1.5550',
          eventLongitude: '104.3030',
        ),
        imagePath: 'assets/images/logoCleanUp.png',
        participantCount: 35,
        totalParticipant: 50,
      ),
      UpcomingEvent(
        eventName: 'Kempen Membersihkan Sekolah',
        eventDate: '15 April 2025',
        eventTime: '09:00 AM - 12:00 PM',
        eventLocation: UpcomingEventLocation(
          eventAddressOne: 'Jalan Sekolah 1',
          eventAddressTwo: 'Berhampiran Masjid Bukit Indah',
          eventState: 'Johor',
          eventPasscode: '81200',
          eventCity: 'Bukit Indah',
          eventLatitude: '1.4820',
          eventLongitude: '103.6760',
        ),
        imagePath: 'assets/images/logoCleanUp.png',
        participantCount: 20,
        totalParticipant: 30,
      ),
      UpcomingEvent(
        eventName: 'Kempen Membersihkan Taman',
        eventDate: '20 April 2025',
        eventTime: '07:30 AM - 09:45 AM',
        eventLocation: UpcomingEventLocation(
          eventAddressOne: 'Taman Tasik Titiwangsa',
          eventAddressTwo: 'Berhadapan dengan KL Tower',
          eventState: 'Kuala Lumpur',
          eventPasscode: '53200',
          eventCity: 'Titiwangsa',
          eventLatitude: '3.1750',
          eventLongitude: '101.7040',
        ),
        imagePath: 'assets/images/logoCleanUp.png',
        participantCount: 50,
        totalParticipant: 100,
      ),
      UpcomingEvent(
        eventName: 'Kempen Membersihkan Kejiranan',
        eventDate: '25 April 2025',
        eventTime: '05:00 PM - 07:00 PM',
        eventLocation: UpcomingEventLocation(
          eventAddressOne: 'Jalan Melawati 3',
          eventAddressTwo: 'Dekat Pasaraya Giant',
          eventState: 'Selangor',
          eventPasscode: '53100',
          eventCity: 'Taman Melawati',
          eventLatitude: '3.2100',
          eventLongitude: '101.7500',
        ),
        imagePath: 'assets/images/logoCleanUp.png',
        participantCount: 15,
        totalParticipant: 25,
      ),
      UpcomingEvent(
        eventName: 'Kempen Membersihkan Pejabat',
        eventDate: '1 Mei 2025',
        eventTime: '02:00 PM - 04:00 PM',
        eventLocation: UpcomingEventLocation(
          eventAddressOne: 'Menara KL, Jalan P Ramlee',
          eventAddressTwo: 'Bersebelahan KL Tower',
          eventState: 'Kuala Lumpur',
          eventPasscode: '50250',
          eventCity: 'Bukit Bintang',
          eventLatitude: '3.1510',
          eventLongitude: '101.7070',
        ),
        imagePath: 'assets/images/logoCleanUp.png',
        participantCount: 10,
        totalParticipant: 20,
      ),
      UpcomingEvent(
        eventName: 'Kempen Membersihkan Lebuhraya',
        eventDate: '5 Mei 2025',
        eventTime: '06:30 AM - 09:00 AM',
        eventLocation: UpcomingEventLocation(
          eventAddressOne: 'Lebuhraya Utara-Selatan (PLUS)',
          eventAddressTwo: 'Kawasan Rehat & Rawat Seremban',
          eventState: 'Negeri Sembilan',
          eventPasscode: '70200',
          eventCity: 'Seremban',
          eventLatitude: '2.7300',
          eventLongitude: '101.9380',
        ),
        imagePath: 'assets/images/logoCleanUp.png',
        participantCount: 40,
        totalParticipant: 50,
      ),
      UpcomingEvent(
        eventName: 'Kempen Membersihkan Sungai',
        eventDate: '10 Mei 2025',
        eventTime: '07:00 AM - 11:00 AM',
        eventLocation: UpcomingEventLocation(
          eventAddressOne: 'Sungai Klang',
          eventAddressTwo: 'Berhampiran Masjid Jamek',
          eventState: 'Selangor',
          eventPasscode: '50050',
          eventCity: 'Klang',
          eventLatitude: '3.0430',
          eventLongitude: '101.4450',
        ),
        imagePath: 'assets/images/logoCleanUp.png',
        participantCount: 60,
        totalParticipant: 80,
      ),
      UpcomingEvent(
        eventName: 'Bengkel Pengurangan Sisa',
        eventDate: '15 Mei 2025',
        eventTime: '10:00 AM - 01:00 PM',
        eventLocation: UpcomingEventLocation(
          eventAddressOne: 'Pusat Eco Pulau Pinang',
          eventAddressTwo: 'Berdekatan Padang Kota Lama',
          eventState: 'Pulau Pinang',
          eventPasscode: '10200',
          eventCity: 'George Town',
          eventLatitude: '5.4140',
          eventLongitude: '100.3290',
        ),
        imagePath: 'assets/images/logoCleanUp.png',
        participantCount: 25,
        totalParticipant: 40,
      ),
    ];
  }
}
