// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAk5IPCfY7nv85FAFNVM7ZtjhCx6QU6GAk',
    appId: '1:29839988288:web:a1d6f1c55c467abbe771a5',
    messagingSenderId: '29839988288',
    projectId: 'clean-up-community-53572',
    authDomain: 'clean-up-community-53572.firebaseapp.com',
    storageBucket: 'clean-up-community-53572.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHmB9yBDlzWEnOr3EJIJhhhfsuuErzt8Q',
    appId: '1:29839988288:android:0080ea49ddd638b4e771a5',
    messagingSenderId: '29839988288',
    projectId: 'clean-up-community-53572',
    storageBucket: 'clean-up-community-53572.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcHT2XzfXbagFciqRVSf1bWqt7F4YRhTc',
    appId: '1:29839988288:ios:5e9944dda294ef5be771a5',
    messagingSenderId: '29839988288',
    projectId: 'clean-up-community-53572',
    storageBucket: 'clean-up-community-53572.firebasestorage.app',
    iosBundleId: 'com.example.cleanUpCommunityApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcHT2XzfXbagFciqRVSf1bWqt7F4YRhTc',
    appId: '1:29839988288:ios:5e9944dda294ef5be771a5',
    messagingSenderId: '29839988288',
    projectId: 'clean-up-community-53572',
    storageBucket: 'clean-up-community-53572.firebasestorage.app',
    iosBundleId: 'com.example.cleanUpCommunityApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAk5IPCfY7nv85FAFNVM7ZtjhCx6QU6GAk',
    appId: '1:29839988288:web:163dfb8be3d566d3e771a5',
    messagingSenderId: '29839988288',
    projectId: 'clean-up-community-53572',
    authDomain: 'clean-up-community-53572.firebaseapp.com',
    storageBucket: 'clean-up-community-53572.firebasestorage.app',
  );

}